Set WshShell = WScript.CreateObject("WScript.Shell")
WScript.Sleep 100
WshShell.SendKeys "9"
WScript.Sleep 100
WshShell.SendKeys "9"
WScript.Sleep 100
WshShell.SendKeys "9"
WScript.Sleep 100
WshShell.SendKeys "6"
WScript.Sleep 100
WshShell.SendKeys "6"
WScript.Sleep 100
WshShell.SendKeys "6"
WScript.Sleep 100
WshShell.SendKeys "{ENTER}"
WScript.Sleep 100
WshShell.SendKeys "9"
WScript.Sleep 100
WshShell.SendKeys "9"
WScript.Sleep 100
WshShell.SendKeys "9"
WScript.Sleep 100
WshShell.SendKeys "6"
WScript.Sleep 100
WshShell.SendKeys "6"
WScript.Sleep 100
WshShell.SendKeys "6"
WScript.Sleep 1000
WshShell.SendKeys "{ENTER}"
